name: Bug Report
description: File a bug report
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: edition
    attributes:
      label: Windows Edition
      description: What edition of Windows 10 are you using
      options:
        - Home
        - Pro
        - Pro for Workstations
        - Enterprise
        - Enterprise LTSC
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other information
      description: Screenshots, suggested fix, other info, etc.